### ISSUE TITLE
Set minDate and maxDate option not working

### ISSUE THREAD

**Issue by sureshrkm** [voronianski/react-pikaday-component#2]
HI ,
Can you pls add some these properties.
1. set MinDate
2. set MaxDate
3. goto Month and Date
4. set Date

**Comment by voronianski** [comment]
@sureshrkm Pikaday options are supported as component attributes - https://github.com/dbushell/Pikaday#configuration

**Comment by edwinj3829** [comment]
How can I update the min and max date?
