### ISSUE TITLE
Call pikaday.destroy() on componentWillUnmount

### ISSUE THREAD

**Issue by joeytrapp** [voronianski/react-pikaday-component#4]
## Description

Component doesn't destory the pikaday object on `componentWillUnmount `.

## Demo link

http://esnextb.in/?gist=9046feb70b2230b6f95c3f41ebce064d

Some error, but demonstrates the issue. Inspect the DOM and there will be a new `<div class="pika-single ..."></div>` after clicking the toggle twice.

**Comment by foxtree** [comment]
Without such a fix, a memory leak  ("detached dom tree") can be detected via Chrome's memory profiler, using heap snapshots before/after mounting this component.
